"""Add donator system

Revision ID: a34076563989
Revises: 
Create Date: 2026-09-06 16:57:12.408559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a34076563989'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genshin_profiles')
    op.add_column('users', sa.Column('moon_shards', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('has_moon', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('crystals_60_claimed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('crystals_330_claimed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('crystals_60_boosted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_donator', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('genshin_uid', sa.String(), nullable=True))
    op.add_column('users', sa.Column('genshin_server', sa.String(), nullable=True))
    op.add_column('wheel_config', sa.Column('prize_type', sa.String(), nullable=True))
    op.add_column('wheel_spins', sa.Column('prize_type', sa.String(), nullable=True))
    op.drop_constraint(op.f('wheel_spins_user_id_fkey'), 'wheel_spins', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('wheel_spins_user_id_fkey'), 'wheel_spins', 'users', ['user_id'], ['id'])
    op.drop_column('wheel_spins', 'prize_type')
    op.drop_column('wheel_config', 'prize_type')
    op.drop_column('users', 'genshin_server')
    op.drop_column('users', 'genshin_uid')
    op.drop_column('users', 'is_donator')
    op.drop_column('users', 'crystals_60_boosted')
    op.drop_column('users', 'crystals_330_claimed')
    op.drop_column('users', 'crystals_60_claimed')
    op.drop_column('users', 'has_moon')
    op.drop_column('users', 'moon_shards')
    op.create_table('genshin_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('server', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('adventure_rank', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('world_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('genshin_profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('genshin_profiles_pkey')),
    sa.UniqueConstraint('uid', name=op.f('genshin_profiles_uid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', name=op.f('genshin_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
